spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
